name = "cloudmail-to-telegram"
main = "src/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[env.production]
name = "cloudmail-to-telegram"

[env.staging]
name = "cloudmail-to-telegram-staging"

# Environment variables (set these as secrets using wrangler secret put)
# TELEGRAM_BOT_TOKEN = "your-bot-token-here"
# TELEGRAM_CHANNEL_ID = "your-channel-id-here"

# Optional: Configure custom domains
# [[env.production.routes]]
# pattern = "mail.yourdomain.com/*"
# zone_name = "yourdomain.com"

# Resource limits
[limits]
memory = 128 # MB

# Optional: Durable Objects for advanced rate limiting (requires paid plan)
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"

# Optional: KV namespace for persistent storage (requires paid plan)
# [[kv_namespaces]]
# binding = "EMAIL_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"